### ISSUE TITLE
taskcluster_login.py: do_GET() is called twice

### ISSUE THREAD

**Issue by JohanLorenzo** [askeing/taskcluster-util-python#22]
# STR

Pre-requisites: Being logged with SSO (not sure if needed, yet)
1. `./taskcluster_login.py`
2. On your web browser, grant the access
3. Go back to your terminal
# Results

```
Started server for listening credentials on localhost:36529
Press ^C will stop server
INFO: Write credentials to /home/jlorenzo/tc_credentials.json
----------------------------------------
Exception happened during processing of request from ('127.0.0.1', 54256)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 295, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 321, in process_request
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib64/python2.7/BaseHTTPServer.py", line 328, in handle_one_request
    method()
  File "./taskcluster_util/taskcluster_login.py", line 98, in do_GET
    k, v = query_item.split('=')
ValueError: need more than 1 value to unpack
----------------------------------------
```

**Comment by JohanLorenzo** [comment]
After some debugging, it turns out [do_GET](https://github.com/askeing/taskcluster-util-python/blob/b96fbfa7f961779c57486dfd5f894a5ddb473730/taskcluster_util/taskcluster_login.py#L91) is called twice. The second time the query is an empty string. This is why there is no value to unpack.

That only occurs when I click "Grant access" in less than 2-3 seconds. If I wait longer, no error is displayed

```
015-11-25 11:11:15,378 - __main__ - DEBUG - ======= GET STARTED =======
2015-11-25 11:11:15,378 - __main__ - DEBUG - Host: localhost:52749
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
2015-11-25 11:11:15,378 - __main__ - DEBUG - GET Parameters: {'certificate': {u'scopes': [u'assume:A_VALID_USER', u'assume:A_VALID_GROUP'], u'expiry': 1448705474325, u'start': 1448445374325, u'version': 1, u'signature': u'A_VALID_SIGNATURE', u'seed': u'A_VALID_SEED'}, 'accessToken': 'A_VALID_TOKEN', 'clientId': 'A_VALID_CLIENT_ID'}
2015-11-25 11:11:15,379 - __main__ - INFO - Write credentials to /home/jlorenzo/tc_credentials.json
2015-11-25 11:11:15,379 - __main__ - DEBUG - ======= Stop Server =======
2015-11-25 11:11:15,522 - __main__ - DEBUG - ======= GET STARTED =======
2015-11-25 11:11:15,522 - __main__ - DEBUG - Host: localhost:52749
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
```

**Comment by askeing** [comment]
#24 fixed it.

**Comment by JohanLorenzo** [comment]
I verified the bug, I agree the error is not displayed anymore. However, I get a worse result: `~/tc_credentials.json` gets written twice, and the second time with an empty object. In orther words, I didn't get credentials and no error message was displayed. Here are the logs:

```
./taskcluster_util/taskcluster_login.py -v 
Do you want to delete /home/jlorenzo/tc_credentials.json? [y/N]y
2015-12-03 11:20:39,342 - __main__ - INFO - Remove file: /home/jlorenzo/tc_credentials.json, backup to /home/jlorenzo/tc_credentials.json.back
Started server for listening credentials on localhost:36898
Press ^C will stop server
2015-12-03 11:20:43,010 - __main__ - DEBUG - ======= GET STARTED =======
2015-12-03 11:20:43,010 - __main__ - DEBUG - Host: localhost:36898
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive

2015-12-03 11:20:43,010 - __main__ - INFO - Temporary credentials will expire on 2015/12/6 11:20.
2015-12-03 11:20:43,010 - __main__ - DEBUG - GET Parameters: {'certificate': {u'scopes': [u'assume:mozilla-user:jlorenzo@mozilla.com', u'assume:mozilla-group:team_moco'], u'expiry': 1449397240916, u'start': 1449137140916, u'version': 1, u'signature': u'JBWW2i/AmEChy5ukxAC9iPdBirIqNC7PMGHuf3lkLc4=', u'seed': u'449s_AzTS22XaDpqTnM0tQ8k0kJ-4aTp2SHmr-C8LNbQ'}, 'accessToken': 'DI-2Ul3QuV28Zftj2X9o9ZcpoI9c3itnOJ-E4GenFHs', 'clientId': 'tc-login'}
2015-12-03 11:20:43,011 - __main__ - INFO - Write credentials to /home/jlorenzo/tc_credentials.json
2015-12-03 11:20:43,011 - __main__ - DEBUG - ======= Stop Server =======
2015-12-03 11:20:43,156 - __main__ - DEBUG - ======= GET STARTED =======
2015-12-03 11:20:43,156 - __main__ - DEBUG - Host: localhost:36898
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive

2015-12-03 11:20:43,156 - __main__ - DEBUG - GET Parameters: {}
2015-12-03 11:20:43,156 - __main__ - INFO - Write credentials to /home/jlorenzo/tc_credentials.json
2015-12-03 11:20:43,157 - __main__ - DEBUG - ======= Stop Server =======
```

@askeing Do you think we should reopen this issue or create a new one?
